### ISSUE TITLE
Проблема с robots.txt

### ISSUE THREAD

**Issue by kellareff** [raosya/web#1]
При обращении к адресу https://yakutia.science/robots.txt ресурс возвращает 500 internal server error.

2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:00 [error] 25152#25152: *432553 rewrite or internal redirection cycle while internally redirecting to "/error/404.html", client: 37.29.41.221, server: yakutia.science, request: "GET /robots.txt HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:02 [error] 25152#25152: *432555 rewrite or internal redirection cycle while internally redirecting to "/error/404.html", client: 37.29.41.221, server: yakutia.science, request: "GET /favicon.ico HTTP/1.1", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/405.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 open() "/var/www/yakutia.science/web/error/404.html" failed (2: No such file or directory), client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"
2019/12/05 23:42:04 [error] 25151#25151: *432558 rewrite or internal redirection cycle while internally redirecting to "/error/404.html", client: 31.25.193.102, server: yakutia.science, request: "GET ///xmlrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock", host: "yakutia.science"

**Comment by TorinAsakura** [comment]
Так а я тут причём? У меня всё работало, я тебе передал дамп, дамп был рабочий, проблемы начались только после переноса, я тут ничего не могу сделать, у меня даже доступа на сервер нет

**Comment by kellareff** [comment]
Доступ есть ключ я твой еще летом устанавливал.
Я конечно могу там в каталоге создать статик. Но ты же поговаривал что у тя на всё там веб хуки стоят. Явно зацикл какойто идет. а в исходы мне точно не залесть

**Comment by TorinAsakura** [comment]
Ключ изменился, я машину сменил
touch > 
```
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
```

**Comment by TorinAsakura** [comment]
И я хз как он у тебя потерялся, я вот щас смотрю архив - файл на месте

**Comment by kellareff** [comment]
Значит в статик.

**Comment by kellareff** [comment]
Хорошо проверю архив.

**Comment by kellareff** [comment]
Видимо не сегодня потомучто уже 00:10 у нас

**Comment by TorinAsakura** [comment]
@kellareff я тебе написал содержимое файла, больше там ничего не нужно, файл должен жить в корне

**Comment by kellareff** [comment]
> @kellareff я тебе написал содержимое файла, больше там ничего не нужно, файл должен жить в корне

Я в курсе.

**Comment by kellareff** [comment]
Исправил
