### ISSUE TITLE
Редактировать раздел “Руководство”

### ISSUE THREAD

**Issue by kellareff** [raosya/web#2]
Ссылка на документ 

https://docs.google.com/document/d/1rdYtxwPFnBhW8itBdUnYUIBxuPqXCpVpJRWPg3D7yHg/edit?usp=sharing

**Comment by TorinAsakura** [comment]
Я что-то не очень понимаю о чём речь. Напиши конкретно кого редактировать и что на что надо поменять, или ты предлагаешь мне так с каждым документом разбираться и сидеть сравнивать данные?

**Comment by kellareff** [comment]
В разделе президиум -> руководство 
Поменять президента на исполняющего обязанности президента  Филиппова  В.В (инфа в ссылке он первый )
Это важно!
И сюда врядли фотки вставиш.

**Comment by TorinAsakura** [comment]
https://yakutia.science/prezidium/rukovodstvo-prezidiuma/ - добавил, жду дополнения данных

**Comment by TorinAsakura** [comment]
https://yakutia.science/prezidium/rukovodstvo-prezidiuma/ - готово, жду обновления инфы
