### ISSUE TITLE
Редактировать раздел Аппарат

### ISSUE THREAD

**Issue by kellareff** [raosya/web#3]
Ссылка на гугл документ
https://drive.google.com/drive/folders/1kv_g55wS5iS2Lp9L0oq2Ns6YYE24VHzk?usp=sharing

**Comment by TorinAsakura** [comment]
Аналогично, детализируй пожалуйста

**Comment by kellareff** [comment]
Так Настя мне скинула. Я просто технически создал задачи.

**Comment by TorinAsakura** [comment]
Это очень круто, что Настя нашла крайнего, но, так работать я не буду, она сюда приглашена, акк у неё есть, расскажи ей как включить 2FA и пускай сама тратит время и расписывает, я не хочу чтобы ты его тратил и уж тем более я не хочу тратить своё

**Comment by kellareff** [comment]
Необходимо внести измениния в разделе Президиум -> Аппарат Академии наук РС(Я)
привести всё в соответствии со спиком ниже, т.е. тех кого в этом списке нет нужно удалить, а оставить только тех кто есть.


Руководитель аппарата Президиума
Семенов Юрий Иванович 
+7(4112)33-57-79 yra_semen1109@mail.ru


Бухгалтерия
Главный бухгалтер - Лучко Лилия Николаевна
+7(4112)39-06-60 anrsya@mail.ru


Отдел закупок
Руководитель - Степанов Иннокентий Васильевич
+7(4112)33-06-66 gz_anrsya@mail.ru


Административно-хозяйственный отдел
Руководитель - Степанов Борис Альбертович
+7(4112)39-06-66 anxch@mail.ru


Отдел кадров
Васильева Туяра Борисовна
+7(4112)33-06-60 tuyaara2012@mail.ru

**Comment by TorinAsakura** [comment]
@kellareff принял в работу

**Comment by kellareff** [comment]
> Это очень круто, что Настя нашла крайнего, но, так работать я не буду, она сюда приглашена, акк у неё есть, расскажи ей как включить 2FA и пускай сама тратит время и расписывает, я не хочу чтобы ты его тратил и уж тем более я не хочу тратить своё

типо так ответом?

**Comment by TorinAsakura** [comment]
@kellareff нет, типа через @ указываешь меня…

**Comment by TorinAsakura** [comment]
> Необходимо внести измениния в разделе Президиум -> Аппарат Академии наук РС(Я)
> привести всё в соответствии со спиком ниже, т.е. тех кого в этом списке нет нужно удалить, а оставить только тех кто есть.
> 
> Руководитель аппарата Президиума
> Семенов Юрий Иванович
> +7(4112)33-57-79 [yra_semen1109@mail.ru](mailto:yra_semen1109@mail.ru)
> 
> Бухгалтерия
> Главный бухгалтер - Лучко Лилия Николаевна
> +7(4112)39-06-60 [anrsya@mail.ru](mailto:anrsya@mail.ru)
> 
> Отдел закупок
> Руководитель - Степанов Иннокентий Васильевич
> +7(4112)33-06-66 [gz_anrsya@mail.ru](mailto:gz_anrsya@mail.ru)
> 
> Административно-хозяйственный отдел
> Руководитель - Степанов Борис Альбертович
> +7(4112)39-06-66 [anxch@mail.ru](mailto:anxch@mail.ru)
> 
> Отдел кадров
> Васильева Туяра Борисовна
> +7(4112)33-06-60 [tuyaara2012@mail.ru](mailto:tuyaara2012@mail.ru)

я просил поменять email адреса
