### ISSUE TITLE
Редактировать раздел Центр интеллектуальной собственности

### ISSUE THREAD

**Issue by kellareff** [raosya/web#5]
Информация на ГД.
https://drive.google.com/drive/folders/1aZEnSrMJIR6SPajDRNA8xxLV6Y8i2f19?usp=sharing

**Comment by TorinAsakura** [comment]
А что редактировать-то я не пойму?Что мне с этими данными нужно сделать?

**Comment by TorinAsakura** [comment]
@akoryakina статус?
