### ISSUE TITLE
Раздел "Руководство"

### ISSUE THREAD

**Issue by akoryakina** [raosya/web#6]
В описании и.о. Президента Филиппова В.В. указать следующую информацию:

Филиппов Василий Васильевич
и.о. Президента Академии наук РС(Я)
Член-корреспондент РАН. Доктор технических наук, профессор. Действительный член Академии наук РС(Я).
Почетный работник высшей школы РФ. Лауреат Государственной премии им. М.К. Аммосова РС(Я) в области государственного строительства. Заслуженный деятель науки РС (Я). Награжден Золотой медалью Академии наук РС (Я).

**Comment by TorinAsakura** [comment]
@akoryakina https://yakutia.science/prezidium/rukovodstvo-prezidiuma/
